# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec_runner}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["T\303\272lio Ornelas"]
  s.date = %q{2011-01-02}
  s.description = %q{GUI Runner for RSpec tests}
  s.email = %q{ornelas.tulio@gmail.com}
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/rspec_runner.rb",
     "lib/rspec_runner/runner.rb",
     "script/console",
     "spec/rspec_runner_spec.rb"
  ]
  s.homepage = %q{http://github.com/tulios/rspec_runner}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{GUI Runner for RSpec tests}
  s.test_files = [
    "spec/rspec_runner_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.1"])
      s.add_development_dependency(%q<rspec-core>, [">= 2.0.1"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.1"])
      s.add_dependency(%q<rspec-core>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.1"])
    s.add_dependency(%q<rspec-core>, [">= 2.0.1"])
  end
end

